AiName: "小忽悠" #ai名称
app: #吟美核心的api配置
  port: 1800  #吟美核心的端口
  mode: ["api"]  # b站直播间:"blivedm"|api web:"api"
searchImg: #搜图服务
  imageNum: 10  # 抽图数量，从中随机一张
  width: 980 # 图片宽度
  height: 500 # 图片高度
  physical_save_folder: "J:\\ai\\ai-yinmei\\porn\\" #绘画保存图片物理路径
  HttpProxies:
searchWeb: #搜索服务
  searchNum: 5  # 抽文数量，从中随机一篇文章
  HttpProxies:
translate: #翻译服务
  HttpProxies: "socks5://127.0.0.1:10806"
danmaku: #弹幕
  blivedm: #b站弹幕
    room_id: 0 #b站直播间号
    sessdata: ""
    ACCESS_KEY_ID: ""
    ACCESS_KEY_SECRET: ""
    APP_ID: 0 # 在B站开放平台创建的项目ID
    ROOM_OWNER_AUTH_CODE: "" # 在B站主播身份码
welcome:
  is_llm_welcome: False #是否llm回复欢迎
  welcome_not_allow: [46130941, 333472479] #是否允许欢迎词
llm: #大模型聊天
  local_llm_type: "fastgpt"  # 1.fastgpt 2.text-generation-webui
  relations: #用户关系
    {
      "程序猿的退休生活": "老爸",
      "未转变者启动不了": "姐姐",
    }
  text-generation-webui: #text-generation-webui
    tgw_url: "http://192.168.2.58:5000/v1/chat/completions" #text-generation-webui服务地址
  fastgpt:   #fastgpt
    fastgpt_url: "https://api.fastgpt.in/api/v1/chat/completions" #fastgpt服务地址，本地：http://192.168.2.198:3000,云端：https://api.fastgpt.in
    fastgpt_authorization: "Bearer fastgpt-mqRBlF37RkqzHxdcvEN7muXzN85oNGuCd8nLSk1scN5CZIvjtehH6" #fastgpt秘钥,本地：fastgpt-kB47BIEdra06DHcCAOfd230Jym98SCBUunptTxdo0D2jxFYun1P5H  云版：fastgpt-mqRBlF37RkqzHxdcvEN7muXzN85oNGuCd8nLSk1scN5CZIvjtehH6
  split_flag: ",|，|。|!|！|?|？|\n" #流式回复的分割符
  split_limit: 4 #流式回复分割的最小字符数量
  public_sentiment_key: "(爱|喵|女仆|老婆|男朋友|比心|媳妇|喜欢|乖|不理你|美|老公)" #舆情关键字判断
draw: #绘画
  HttpProxies: { "http": "socks5://127.0.0.1:10806", "https": "socks5://127.0.0.1:10806" }
  drawUrl: "http://192.168.2.57:7860" #Stable Diffusion服务ip
  width: 980 # 图片宽度
  height: 500 # 图片高度
  physical_save_folder: "J:\\ai\\ai-yinmei\\porn\\" #绘画保存图片物理路径
sing: #唱歌
  singUrl: "http://192.168.2.58:1717" #Auto-Convert-Music服务ip
  song_not_convert: "(三国演义\\d+|粤剧|京剧|易经)" #不需要学习的歌曲【支持正则】
  create_song_timout: 500 #超时生成歌曲
emote: #vts表情
  switch: True  #vtuber开关：True-开，False-关
  vtuber_websocket: "127.0.0.1:8001" #Vtuber Studio服务ip
  vtuber_pluginName: "winlonebot"
  vtuber_pluginDeveloper: "winlone"
  vtuber_authenticationToken: "27605d6e478a0ff6bd39c3a7496efa7b1d1269ab2735901c21e201db158ab16c"
nsfw: #鉴黄
  nsfw_server: "http://192.168.2.57:1801"
  filterEn: "huge breasts,open clothes,topless,voluptuous,breast,prostitution,erotic,armpit,milk,leaking,spraying,woman,cupless latex,latex,tits,boobs,lingerie,chest,seductive,poses,pose,leg,posture,alluring,milf,on bed,mature,slime,open leg,full body,bra,lace,bikini,full nude,nude,bare,one-piece,navel,cleavage,swimsuit,naked,adult,nudity,beautiful breasts,nipples,sex,Sexual,vaginal,penis,large penis,pantie,leotards,anal"
  filterCh: "奶子,乳房" #过滤弹幕
  progress_limit: 1 #绘图大于多少百分比进行鉴黄，这里设置了1%
  nsfw_limit: 0.2 #nsfw黄图值大于多少进行绘画屏蔽【值越大越是黄图，值范围0~1】
  nsfw_progress_limit: 0.2 #nsfw黄图-绘画进度鉴黄【值越大越是黄图，值范围0~1】
speech: #语音
  select: "edge-tts"  #edge-tts、gpt-sovits、bert-vists
  bert-vists:
    bert_vists_url: "http://192.168.2.57:5000"
    speaker_name: "珊瑚宫心海[中]"
    sdp_ratio: 0.2 #SDP在合成时的占比，理论上此比率越高，合成的语音语调方差越大
    noise: 0.2 #控制感情变化程度，默认0.2
    noisew: 0.9 #控制音节发音变化程度，默认0.9
    speed: 1 #语速
  gpt-sovits:
    gtp_vists_url: "http://192.168.2.57:9880" #gtp-vists服务ip
  edge-tts:
    speaker_name: "zh-CN-XiaoxiaoNeural"
  speech_max_threads: 5 #语音合成线程池
obs: #obs直播软件
  switch: True  #obs开关：True-开，False-关
  url: "192.168.2.198" #OBS直播软件的websocket ip
  port: 4455
  password: "123456"
  dance_path: "H:\\人工智能\\ai\\跳舞视频\\横屏" #跳舞视频所在路径，支持子文件夹
  emote_path: "H:\\人工智能\\ai\\跳舞视频\\表情" #表情视频所在路径，支持子文件夹
  emote_font: "H:\\人工智能\\ai\\跳舞视频\\表情\\表情符号" #表情视频的名称列表
  song_background:
    {
      "海岸花坊": "J:\\ai\\背景音乐\\海岸花坊.rm",
      "神社": "J:\\ai\\背景音乐\\神社.mp3",
      "清晨房间": "J:\\ai\\背景音乐\\清晨房间.mp3",
      "粉色房间": "J:\\ai\\背景音乐\\粉色房间.rm",
      "花房": "J:\\ai\\背景音乐\\花房.mp3",
    }
